name: Auto Release
on:
  push:
    tags:
      - 'v*.*'
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
        python setup.py install
    - name: Set up Git and switch to Master
      run: |
        git config --local user.email "tugan@berkeley.edu"
        git config --local user.name "Gan Tu"
        git checkout master
    - name: Generate documentation using pdoc
      run: |
        rm -rf docs/*
        pdoc3 ganutils --html -o docs --force
        mv docs/ganutils/* docs/
        rm -rf docs/ganutils
    - name: Git commit new documentation
      run: |
        git add -A
        git commit -m "docs: automated update to docs/ doumentation [GitHub Action]" || echo "No documentation changes"
    - name: Push documentation changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
    - name: Release new version
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
