name: Automated Docs Generation
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
        python setup.py install
    - name: Generate documentation using pdoc
      run: |
        pdoc3 ganutils --html -o docs --force
        mv docs/ganutils/* docs/
        rm -rf docs/ganutils
    - name: Git commit new documentation
      run: |
        git config --local user.email "tugan@berkeley.edu"
        git config --local user.name "Gan Tu"
        git add -A
        git commit -m "docs: automated update to docs/ doumentation [GitHub Action]"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
